fixed Dockerfile

diff --git a/ansible-workspace/Dockerfiles/Dockerfile b/ansible-workspace/Dockerfiles/Dockerfile
--- a/ansible-workspace/Dockerfiles/Dockerfile
+++ b/ansible-workspace/Dockerfiles/Dockerfile
@@ -12,12 +12,10 @@ FROM registry.redhat.io/ubi8/ubi-minimal:latest
 
 USER root
 
-ENV HOME=/home/jboss \
+ENV HOME=/home/user \
     PATH=/usr/bin:$PATH \
     PYTHON_VERSION="3.8" \
-    MANPATH="/usr/share/man:${MANPATH}" \
-    XDG_CONFIG_DIRS="/etc/xdg:${XDG_CONFIG_DIRS:-/etc/xdg}" \
-    XDG_DATA_DIRS="/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}" 
+    MANPATH="/usr/share/man:${MANPATH}"
 
 RUN microdnf install -y yum && \
     microdnf clean all && \
@@ -26,27 +24,10 @@ RUN microdnf install -y yum && \
     yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS && \
     PYTHON_PKGS="python38 python38-devel python3-virtualenv python38-setuptools python38-setuptools-wheel" && \
     yum -y module reset python38 && \
-    yum -y module enable python38:3.8 && \
+    yum -y module enable python38:${PYTHON_VERSION} && \
     yum -y --setopt=tsflags=nodocs install $PYTHON_PKGS && \
     yum -y update && \
-    yum -y -q clean all && rm -rf /var/cache/yum && \
-    # TODO: why do we need this jboss user?
-    useradd -u 1000 -G wheel,root -d ${HOME} --shell /bin/bash -m jboss && \
-    mkdir -p ${HOME}/che /projects && \
-    chown 1000 ${HOME} && \
-    for f in "${HOME}" "/etc/passwd" "/etc/group" "/projects"; do \
-        chgrp -R 0 ${f} && \
-        chmod -R g+rwX ${f}; \
-    done && \
-    # Generate passwd.template \
-    cat /etc/passwd | \
-    sed s#jboss:x.*#jboss:x:\${USER_ID}:\${GROUP_ID}::\${HOME}:/bin/bash#g \
-    > ${HOME}/passwd.template && \
-    # Generate group.template \
-    cat /etc/group | \
-    sed s#root:x:0:#root:x:0:0,\${USER_ID}:#g \
-    > ${HOME}/group.template && \
-    echo "jboss	ALL=(ALL)	NOPASSWD: ALL" >> /etc/sudoers  \
+    yum -y -q clean all && rm -rf /var/cache/yum
 
 RUN \
     echo "updates pip" && \
@@ -54,7 +35,10 @@ RUN \
     python3.8 -m pip install -U virtualenv && \
     ln -s /usr/bin/python3.8 /usr/bin/python && \
     ln -s /usr/bin/pip3.8 /usr/bin/pip 
-    
+
+SHELL ["/bin/bash", "-c"]
+RUN command -v source || (echo "ERROR: Could not find 'source' command. SHELL may not supported. If you are using podman, try again with the '--format docker' flag." && exit 126)
+
 RUN \
     # cleanup and summaries
     echo "Installed Packages" && rpm -qa | sort -V && echo "End Of Installed Packages" && \
@@ -63,32 +47,26 @@ RUN \
     pip -V && \
     echo "========"
 
-ADD entrypoint.sh ${HOME}/
-ADD requirements.txt ${HOME}/
-RUN chmod +x ${HOME}/*.sh
+RUN mkdir -p "${HOME}" && cd "${HOME}" && \
+    python -m venv .venv && \
+    source .venv/bin/activate && \
+    pip install -U pylint ansible ansible-lint && \
+    mv "${HOME}"/.venv "${HOME}"/.venv-tmp
 
-USER jboss
+COPY --chown=0:0 etc/entrypoint.sh /entrypoint.sh
+
+RUN mkdir /projects && chmod +x /entrypoint.sh \
+    # Change permissions to let any arbitrary user
+    for f in "${HOME}" "/etc/passwd" "/projects"; do \
+      echo "Changing permissions on ${f}" && chgrp -R 0 ${f} && \
+      chmod -R g+rwX ${f}; \
+    done
+
+USER 10001
+ENV HOME=/home/user
 WORKDIR /projects
-RUN \
-python -m virtualenv ${HOME}/ansible2.9 && \
-source ${HOME}/ansible2.9/bin/activate && \
-python -m pip install "ansible == 2.9.21" && \
-python -m pip install ansible-lint && \
-python -m pip install -r ${HOME}/requirements.txt && \
-chgrp -R 0 ${HOME}/ansible2.9 && \
-chmod -R g+rwX ${HOME}/ansible2.9 && \
-deactivate && \
-python -m virtualenv ${HOME}/ansible2.11 && \
-source ${HOME}/ansible2.11/bin/activate && \
-python -m pip install "ansible-core == 2.11.5" && \
-python -m pip install ansible-lint && \
-python -m pip install ansible-builder && \
-python -m pip install -r ${HOME}/requirements.txt && \
-chgrp -R 0 ${HOME}/ansible2.11 && \
-chmod -R g+rwX ${HOME}/ansible2.11 && \
-deactivate 
-ENTRYPOINT ["/home/jboss/entrypoint.sh"]
-CMD tail -f /dev/null
+ENTRYPOINT [ "/entrypoint.sh" ]
+CMD ["tail", "-f", "/dev/null"]
 
 # append metadata here
 ENV SUMMARY="Red Hat CodeReady Workspaces - RHEL 8 + Python 3.8 + Ansible container" \
